Changes to README.md
DarthStrom/MockingBird pull request #16
Opened 2017-07-20 22:48 UTC by michaelrauh

This makes a few changes to the README.md

The most salient change is that there is a discussion of making mocks extend or conform to the protocol of the object that is being mocked. Additionally, in most of the examples, the class that is being mocked is included in the example. 

The largest downside that I can see in these changes is that it increases the length of the README significantly. Additionally, some of the explanations are wordy. 

If there are any changes that would make this make more sense, please let me know. On the other hand, if this change is rejected I will not be offended.

2017-07-20 23:14 UTC, DarthStrom requested changes
Looks great overall.  Thanks for submitting!

2017-07-20 23:14 UTC, DarthStrom commented on README.md
> +###  Extension
Should we say Inheritance here?  I think extension generally means `extend ExampleClass {` etc.

2017-07-20 23:14 UTC, DarthStrom commented on README.md
> +class MockClass: Mock {
Maybe we should have most examples use protocols instead of classes to be more Swifty.

2017-07-20 23:14 UTC, DarthStrom commented on README.md
> +    override func foo(id: Int, name: String) -> Bool {
I like `foo` - `validate` was confusing.

2017-07-20 23:14 UTC, DarthStrom commented on README.md
> +First, make a mock object that conforms to the Mock protocol with an instance of Moxie, and which is also of the same type as the object being mocked
...the same type or conform to the same protocol...?

2017-07-20 23:14 UTC, DarthStrom commented on README.md
>      func testUpdateWasNotCalled() {
these test names need updated (see what I did there?)

2017-07-21 00:50 UTC, michaelrauh commented on README.md
> +class MockClass: Mock {
That would be Swiftier! I've changed all but the one example to use protocols. Please let me know if I've gone too far.

2017-07-21 00:51 UTC, michaelrauh commented on README.md
> +###  Extension
I admit, I didn't think of that. I changed it.

2017-07-21 00:51 UTC, michaelrauh commented on README.md
> +    override func foo(id: Int, name: String) -> Bool {
Thanks! I've tried to keep it clear what is [INSERT CODE HERE] and what is actually important to the README

2017-07-21 00:52 UTC, michaelrauh commented on README.md
> +First, make a mock object that conforms to the Mock protocol with an instance of Moxie, and which is also of the same type as the object being mocked
Good call, that was awkward. Does this make more sense?

2017-07-21 00:53 UTC, michaelrauh commented on README.md
>      func testUpdateWasNotCalled() {
These test names have foo

2017-07-21 00:59 UTC, DarthStrom commented on README.md
> +    func testFooCalledWithBlankByDefault() {
I don't remember what `BlankByDefault` means, but it should probably be something like `testFooWasCalled`.

2017-07-21 01:27 UTC, michaelrauh commented on README.md
> +    func testFooCalledWithBlankByDefault() {
It looks like I somehow glossed over that. Thank you for the spot!

2017-07-21 01:27 UTC, DarthStrom approved these changes

2017-07-21 01:56 UTC, merged